# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20170429_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='location_city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location_country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
