# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20170508_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='location_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.CITIES_CITY_MODEL),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.CITIES_COUNTRY_MODEL),
        ),
    ]
